# Generated by Django 3.0.3 on 2021-01-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='profile_picture/')),
                ('mob_no', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
